name: Add Label

on:
    issue_comment:
        types: [created]

jobs:
    add-label:
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/lgtm')
        runs-on: ubuntu-latest
        steps:
            - name: Add LGTM label
              uses: actions/github-script@v5
              with:
                  github-token: ${{secrets.CI_GITHUB_TOKEN}}
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'LGTM 라벨이 추가되었습니다.'
                      })


